import React, { useState, useEffect } from "react";
import { Flame, Activity, TrendingUp, Newspaper, Cpu, Sparkles, RefreshCw, AlertTriangle, CalendarPlus, Check, ExternalLink, Award, PlayCircle } from "lucide-react";
import { scheduleCalendarEvent } from "../lib/workspace";

interface StockRecommendation {
  symbol: string;
  name: string;
  volatility: string;
  volume: string;
  news: string;
  technicalIndicators: string;
  rationale: string;
  entryTrigger: number;
  targetPrice: number;
  stopLoss: number;
  riskRewardRatio: number;
}

interface RecommendationEngineProps {
  onSelectTicker: (symbol: string) => void;
  onProposeTicker: (symbol: string) => void;
  accessToken: string | null;
  isAiEnabled: boolean;
}

export default function RecommendationEngine({ onSelectTicker, onProposeTicker, accessToken, isAiEnabled }: RecommendationEngineProps) {
  const [recommendations, setRecommendations] = useState<StockRecommendation[]>([]);
  const [sources, setSources] = useState<{ title: string; uri: string }[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isFallback, setIsFallback] = useState(false);

  // Calendar states
  const [schedulingCalendar, setSchedulingCalendar] = useState<string | null>(null); // maps to symbol
  const [calendarSuccess, setCalendarSuccess] = useState<Record<string, string>>({}); // symbol -> link
  const [calendarError, setCalendarError] = useState<string | null>(null);

  useEffect(() => {
    fetchRecommendations();
  }, []);

  const fetchRecommendations = async () => {
    setLoading(true);
    setError(null);
    setIsFallback(false);
    try {
      const res = await fetch("/api/gemini/recommendations");
      if (!res.ok) {
        let errorMsg = "Failed to fetch day trading recommendations.";
        try {
          const errData = await res.json();
          errorMsg = errData.error || errorMsg;
        } catch (e) {}
        throw new Error(errorMsg);
      }
      const text = await res.text();
      if (!text) throw new Error("Empty response from recommendation engine.");
      const data = JSON.parse(text);
      setRecommendations(data.recommendations || []);
      setSources(data.sources || []);
      setIsFallback(!!data.fallback);
    } catch (err: any) {
      console.log("Recommendations fetch error");
      setError(err.message || "Unable to retrieve recommendation feed.");
    } finally {
      setLoading(false);
    }
  };

  const scheduleOnCalendar = async (rec: StockRecommendation) => {
    if (!accessToken) return;
    setSchedulingCalendar(rec.symbol);
    setCalendarError(null);

    // Tomorrow at market open (9:30 AM EST)
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    tomorrow.setHours(9, 30, 0, 0);
    const endHour = new Date(tomorrow.getTime() + 60 * 60 * 1000); // 1 hr session

    const eventData = {
      summary: `Day Trade Execution Plan: ${rec.symbol}`,
      description: `Tactical Trade Setup generated by Sera's Stock Day Trader Engine.
Company: ${rec.name}
Entry Trigger Level: $${rec.entryTrigger.toFixed(2)}
Profit Exit Limit: $${rec.targetPrice.toFixed(2)}
Capital Stop Loss Guard: $${rec.stopLoss.toFixed(2)}
Risk-to-Reward Ratio: ${rec.riskRewardRatio}x
Technical Setup: ${rec.technicalIndicators}
Sera's Tactical Rationale: ${rec.rationale}
News Catalyst: ${rec.news}`,
      startDateTime: tomorrow.toISOString(),
      endDateTime: endHour.toISOString(),
    };

    try {
      const result = await scheduleCalendarEvent(accessToken, eventData);
      if (result) {
        setCalendarSuccess((prev) => ({
          ...prev,
          [rec.symbol]: result.htmlLink || "#",
        }));
      }
    } catch (err: any) {
      setCalendarError(err.message || "Failed to schedule Calendar Event.");
    } finally {
      setSchedulingCalendar(null);
    }
  };

  return (
    <div id="day-trade-recommendation-engine" className="space-y-6">
      
      {/* Alert status banner for fallback or errors */}
      {isFallback && (
        <div className="bg-amber-500/10 border border-amber-500/20 text-amber-400 p-4 rounded-xl flex items-start gap-3 text-xs leading-relaxed font-mono text-left">
          <AlertTriangle className="shrink-0 text-amber-400" size={18} />
          <div>
            <p className="font-bold uppercase">Using Static High-Fidelity Recommendations</p>
            <p className="mt-1">
              To trigger live, real-time Gemini web-grounded stock scan recommendations with live premarket volumes, configure your <span className="text-white font-bold">GEMINI_API_KEY</span> in the <span className="text-white font-bold">Settings &gt; Secrets</span> workspace panel. Active liquid technical setups are loaded as standby.
            </p>
          </div>
        </div>
      )}

      {/* Main Header Card */}
      <div className="bg-neutral-900 border border-neutral-850 rounded-2xl p-6 text-left relative overflow-hidden">
        <div className="absolute top-0 right-0 h-40 w-40 bg-emerald-500/5 blur-3xl rounded-full" />
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse" />
              <h3 className="font-bold text-lg text-white font-sans tracking-tight">Recommendations AI Scanner Engine</h3>
            </div>
            <p className="text-xs text-neutral-400 leading-relaxed mt-1 max-w-2xl">
              Analyzing structural relative trading volume, historical standard deviations, real-time news catalysts, and multi-timeframe moving averages to pinpoint top intra-day setups.
            </p>
          </div>
          <button
            onClick={() => isAiEnabled && fetchRecommendations()}
            disabled={loading || !isAiEnabled}
            className={`flex items-center gap-2 font-mono text-xs px-4 py-2 rounded-xl transition-all self-start md:self-auto ${
              !isAiEnabled
                ? "bg-neutral-800 text-neutral-500 cursor-not-allowed opacity-50 border border-neutral-700"
                : "bg-neutral-950 border border-neutral-800 hover:border-emerald-500/30 text-neutral-300 hover:text-emerald-400 cursor-pointer"
            }`}
          >
            <RefreshCw size={13} className={loading ? "animate-spin" : ""} />
            {loading ? "SCANNING GLOBAL EXCHANGES..." : isAiEnabled ? "SCAN VOLATILITY MOVERS" : "AI SCAN LOCKED"}
          </button>
        </div>
      </div>

      {loading ? (
        <div className="py-24 text-center">
          <RefreshCw className="animate-spin mx-auto text-emerald-400 mb-4" size={32} />
          <p className="text-sm text-neutral-400 font-mono uppercase tracking-wider">Evaluating relative premarket volume & sector beta catalysts...</p>
        </div>
      ) : error ? (
        <div className="bg-rose-500/10 border border-rose-500/20 text-rose-400 p-6 rounded-2xl text-center">
          <AlertTriangle className="mx-auto text-rose-400 mb-2" size={28} />
          <p className="font-mono text-xs uppercase font-bold">Failed to load recommendations</p>
          <p className="text-xs text-neutral-400 mt-1">{error}</p>
          <button
            onClick={fetchRecommendations}
            className="mt-4 bg-neutral-950 border border-neutral-800 text-xs px-4 py-2 rounded-xl hover:border-emerald-500/30 transition-all cursor-pointer text-neutral-300"
          >
            Retry Connection Scan
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {recommendations.map((rec, index) => {
            const calendarId = `rec-${rec.symbol}-${index}`;
            return (
              <div
                key={index}
                className="group bg-neutral-900 border border-neutral-800 hover:border-emerald-500/40 hover:bg-neutral-900/80 p-6 rounded-2xl flex flex-col justify-between text-left transition-all duration-300 relative overflow-hidden"
              >
                {/* Visual Highlight Overlay */}
                <div className="absolute top-0 right-0 h-16 w-16 bg-emerald-500/[0.01] group-hover:bg-emerald-500/[0.03] blur-xl rounded-full transition-all duration-300" />
                
                <div>
                  {/* Top Header: Symbol & Quick Action */}
                  <div className="flex items-start justify-between border-b border-neutral-800/60 pb-3 mb-4">
                    <div>
                      <div className="flex items-center gap-2">
                        <h4 className="font-bold text-xl font-mono text-white tracking-tight group-hover:text-emerald-400 transition-colors">
                          {rec.symbol}
                        </h4>
                        <span className="px-2 py-0.5 rounded text-[9px] font-mono font-bold border border-emerald-500/20 bg-emerald-500/5 text-emerald-400 uppercase tracking-wider">
                          Active Intraday Scalp
                        </span>
                      </div>
                      <p className="text-xs text-neutral-400 font-sans mt-0.5">{rec.name}</p>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => onProposeTicker(rec.symbol)}
                        className="p-1.5 rounded-lg bg-neutral-950 border border-neutral-850 text-neutral-400 hover:text-emerald-400 hover:border-emerald-500/30 transition-all cursor-pointer"
                        title="Visualize Live Chart"
                      >
                        <PlayCircle size={15} />
                      </button>
                      
                      {accessToken && (
                        <button
                          onClick={() => scheduleOnCalendar(rec)}
                          disabled={schedulingCalendar !== null}
                          className="p-1.5 rounded-lg bg-neutral-950 border border-neutral-850 text-neutral-400 hover:text-emerald-400 hover:border-emerald-500/30 transition-all cursor-pointer"
                          title="Schedule Trade Setup on Calendar"
                        >
                          {schedulingCalendar === rec.symbol ? (
                            <RefreshCw size={15} className="animate-spin" />
                          ) : calendarSuccess[rec.symbol] ? (
                            <Check size={15} className="text-emerald-400" />
                          ) : (
                            <CalendarPlus size={15} />
                          )}
                        </button>
                      )}
                    </div>
                  </div>

                  {calendarSuccess[rec.symbol] && (
                    <div className="mb-4 bg-emerald-500/10 border border-emerald-500/20 text-[10px] text-emerald-400 px-3 py-1.5 rounded-xl flex justify-between items-center font-mono">
                      <span>Trade execution scheduled!</span>
                      <a href={calendarSuccess[rec.symbol]} target="_blank" rel="noreferrer" className="text-white font-bold underline hover:no-underline flex items-center gap-0.5">
                        Open Calendar Event <ExternalLink size={10} />
                      </a>
                    </div>
                  )}

                  {/* Core Factors Section */}
                  <div className="space-y-3">
                    
                    {/* Volatility & Volume Panel */}
                    <div className="grid grid-cols-2 gap-3">
                      <div className="bg-neutral-950/60 border border-neutral-850 p-2.5 rounded-xl">
                        <div className="flex items-center gap-1.5 text-neutral-400 text-[10px] font-bold uppercase tracking-wider mb-1">
                          <Flame size={12} className="text-amber-500" />
                          Volatility Profile
                        </div>
                        <p className="text-xs font-mono font-bold text-neutral-200">{rec.volatility}</p>
                      </div>

                      <div className="bg-neutral-950/60 border border-neutral-850 p-2.5 rounded-xl">
                        <div className="flex items-center gap-1.5 text-neutral-400 text-[10px] font-bold uppercase tracking-wider mb-1">
                          <Activity size={12} className="text-emerald-400" />
                          Volume Status
                        </div>
                        <p className="text-xs font-mono font-bold text-neutral-200">{rec.volume}</p>
                      </div>
                    </div>

                    {/* Catalyst News */}
                    <div className="bg-neutral-950/40 border border-neutral-850/60 p-3 rounded-xl text-xs">
                      <div className="flex items-center gap-1.5 text-neutral-400 text-[10px] font-bold uppercase tracking-wider mb-1.5 font-mono">
                        <Newspaper size={12} className="text-emerald-400" />
                        Catalyst News Pulse
                      </div>
                      <p className="text-neutral-300 leading-relaxed font-sans">{rec.news}</p>
                    </div>

                    {/* Technical Indicators */}
                    <div className="bg-neutral-950/40 border border-neutral-850/60 p-3 rounded-xl text-xs">
                      <div className="flex items-center gap-1.5 text-neutral-400 text-[10px] font-bold uppercase tracking-wider mb-1.5 font-mono">
                        <Cpu size={12} className="text-cyan-400" />
                        Technical Indicators Scanner
                      </div>
                      <p className="text-neutral-300 leading-relaxed font-sans">{rec.technicalIndicators}</p>
                    </div>

                    {/* Sera's Tactical Rationale */}
                    <div className="border-l-2 border-emerald-500/40 pl-3.5 py-1.5 my-3 bg-emerald-500/[0.01]">
                      <div className="flex items-center gap-1 text-[10px] text-emerald-400 font-bold uppercase tracking-widest mb-1 font-mono">
                        <Sparkles size={11} /> Sera's AI Trading Rationale
                      </div>
                      <p className="text-xs text-neutral-300 italic font-sans leading-relaxed">
                        "{rec.rationale}"
                      </p>
                    </div>

                  </div>
                </div>

                {/* Day-Trading Setup parameters pill */}
                <div className="mt-6 pt-4 border-t border-neutral-800/60">
                  <div className="flex items-center gap-1 text-[10px] text-neutral-500 uppercase tracking-widest mb-2 font-mono">
                    <TrendingUp size={11} className="text-emerald-400" /> Game-Plan Setup
                  </div>
                  <div className="grid grid-cols-4 gap-2 text-center font-mono bg-neutral-950 border border-neutral-850 rounded-xl p-2.5">
                    <div>
                      <p className="text-[8px] text-neutral-500 uppercase">Entry Limit</p>
                      <p className="text-xs font-bold text-emerald-400">${rec.entryTrigger.toFixed(2)}</p>
                    </div>
                    <div>
                      <p className="text-[8px] text-neutral-500 uppercase">Target Exit</p>
                      <p className="text-xs font-bold text-white">${rec.targetPrice.toFixed(2)}</p>
                    </div>
                    <div>
                      <p className="text-[8px] text-neutral-500 uppercase">Stop Guard</p>
                      <p className="text-xs font-bold text-rose-400">${rec.stopLoss.toFixed(2)}</p>
                    </div>
                    <div>
                      <p className="text-[8px] text-neutral-500 uppercase">R:R Ratio</p>
                      <p className="text-xs font-bold text-emerald-400 flex items-center justify-center gap-0.5">
                        <Award size={11} /> {rec.riskRewardRatio}x
                      </p>
                    </div>
                  </div>
                </div>

              </div>
            );
          })}
        </div>
      )}

      {/* Sources footer citation */}
      {!loading && sources.length > 0 && (
        <div className="text-left bg-neutral-900 border border-neutral-850/80 rounded-xl p-4">
          <p className="text-[9px] font-mono text-neutral-500 uppercase tracking-wider mb-2">Sources Checked for Recommendation Accuracy (No Assumptions):</p>
          <div className="flex flex-wrap gap-2">
            {sources.map((s, idx) => (
              <a
                key={idx}
                href={s.uri}
                target="_blank"
                referrerPolicy="no-referrer"
                className="flex items-center gap-1 text-[10px] bg-neutral-950 hover:bg-neutral-800 border border-neutral-850 px-2.5 py-1 rounded-lg text-neutral-400 hover:text-white font-mono transition-colors"
              >
                {s.title.substring(0, 24)}... <ExternalLink size={10} />
              </a>
            ))}
          </div>
        </div>
      )}

    </div>
  );
}
